#!/usr/bin/env python
import os
import sys
import string
equation = sys.argv[1]
membre_second = ""
membre_premier = ""
a = ""
b = ""
c = ""
delta = ""
if (len(sys.argv) > 2):
    print "Trop d'arguments"
    sys.exit(0)
if (equation.count("=") != 1):
    print "Nombre de signes \'=\' incorrect"
    sys.exit(0)
equation = equation.replace(' ', '')
#equation = equation.replace('X^0', '1')
#equation = equation.replace('^', '**')
index = equation.find('=')
i = 0
while i < index:
    membre_premier += equation[i]
    i += 1
i = index
while i < len(equation):
    if (equation[index + 1] == '-' and i == index):
        membre_second += '+'
        i = index + 2;
    elif (equation[index + 1] == '+' and i == index):
        membre_second += '-'
        i = index + 2;
    elif (i == index):
        membre_second += '-'
        i = index + 1;
    if(equation[i] == '-'):
        membre_second += '+'
    elif (equation[i] == '+'):
        membre_second += '-'
    else:
        membre_second += equation[i]
    i += 1


    """
    while i < len(equation):
        i = equation.find('*X^1', i)
        j = i-1
        if i != -1:
            p1 = ""
            while (j >0 and (equation[j] != '-' and equation[j] != '+')):
                p1 += equation[j]
                j -= 1
            p1 += equation[j]
            p1 = p1[::-1]
            indexp1.append(p1)
        else:
            break
        i += 4
    i = 0
    p1 = ""
    while (i < len(indexp1)):
        p1 += indexp1[i]
        i += 1
    print str(eval(p1)) + "*X^1"



    while i < len(equation):
        i = equation.find('*X^2', i)
        j = i-1
        if i != -1:
            p2 = ""
            while (j >0 and (equation[j] != '-' and equation[j] != '+')):
                p2 += equation[j]
                j -= 1
            p2 += equation[j]
            p2 = p2[::-1]
            indexp2.append(p2)
        else:
            break
        i += 4
    i = 0
    p2 = ""
    while (i < len(indexp2)):
        p2 += indexp2[i]
        i += 1
    print str(eval(p2)) + "*X^2"
    """
print membre_second
#membre_second = eval(membre_second + "*(-1)")
#print membre_premier
#print membre_second
#equation = membre_premier + str(membre_second)
#print equation + "=0"
#print "Result = " + str(eval(equation))
